config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/feedback', to: 'pages#feedback'

  get '/cleaning', to:'pages#cleaning'

  get '/labor', to: 'pages#labor'

  get '/personal', to: 'pages#personal'

  get '/build', to: 'pages#build'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def feedback
  end

  def cleaning
  end

  def labor
  end

  def personal
  end

  def build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ozenith</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://code.jquery.com/jquery.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
<div class="page-header">
  <h1><%= yield(:title)%></h1>
</div>
</div>

<div class="container">
<%=render 'shared/nav' %>
</div>

<%= yield %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'All About Us')%>

<%= render 'shared/jumbotron' %>

app/views/pages/build.html.erb
<% provide(:title, 'The Builder Bot')%>
<% provide(:pose, image_tag('BuildBotPose.jpg', class: "pic"))%>
<%= render 'shared/jumbotron' %>

app/views/pages/cleaning.html.erb
<% provide(:title, 'Cleaning Bot')%>
<% provide(:pose, image_tag('CleaningBotPose.jpg', class: "pic"))%>
<%= render 'shared/jumbotron' %>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact the Programmer')%>

<%= render 'shared/jumbotron' %>

app/views/pages/feedback.html.erb
<% provide(:title, 'Leave some Feedback')%>

<%= render 'shared/jumbotron' %>

app/views/pages/home.html.erb
<% provide(:title, 'Home')%>
<div class="container">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
	<li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>
 
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("bot1.jpg") %>
      <div class="carousel-caption">
          <%= link_to "Lets Clean", cleaning_path, class: "btn btn-lg btn-danger" %>
          <h3 class="BlackText">Cleaning Bot v1.0</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag("bot2.jpg") %>
      <div class="carousel-caption">
          <%= link_to "Lets Build", build_path, class: "btn btn-lg btn-danger" %>
          <h3 class="BlackText">Build Bot v1.0</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag("bot3.jpg") %>
      <div class="carousel-caption">
		  <%= link_to "Lets get Personal", personal_path, class: "btn btn-lg btn-danger" %>
		  <h3 class="BlackText">Personal Bot v1.0</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag("bot4.jpg") %>
      <div class="carousel-caption">
		  <%= link_to "Just Basic Labor", labor_path, class: "btn btn-lg btn-danger" %>
		  <h3 class="BlackText">Labor Bot v1.0</h3>
      </div>
    </div>
  </div>
 
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div> <!-- Carousel -->
</div>

	

app/views/pages/labor.html.erb
<% provide(:title, 'Plain ole Labor')%>
<% provide(:pose, image_tag('LaborBotPose.jpg', class: "pic"))%>
<%= render 'shared/jumbotron' %>

app/views/pages/personal.html.erb
<% provide(:title, 'Personal Bot')%>
<% provide(:pose, image_tag('PersonaBotPose.jpg', class: "pic"))%>
<%= render 'shared/jumbotron' %>

app/views/shared/_jumbotron.html.erb
<div class="container">
<div class="jumbotron">
	<div >
	<%= yield(:pose) %>
    </div>
  <h1>#</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Set Up an Appointment with a Programmer</a></p>
  <br class="clear"/>
</div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href=<%= contact_path  %>>Get a Bot <span class="sr-only">(current)</span></a></li>
        <li><a href=<%= about_path  %>>About Us</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">All The Bots <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= cleaning_path  %>>Cleaning Bot</a></li>
            <li><a href=<%= build_path  %>>Building Bot</a></li>
            <li><a href=<%= labor_path  %>>Labor Bot</a></li>
            <li><a href=<%= personal_path  %>>Personal Bot</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Bots coming SOON!</a></li>
          </ul>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>